# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\x12\x0bgrpcPackage\"\r\n\x0bvoidNoParam\"\x12\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\"\x13\n\x05Items\x12\n\n\x02id\x18\x01 \x01(\x05\x32=\n\x04Todo\x12\x35\n\ncreateItem\x12\x11.grpcPackage.Item\x1a\x12.grpcPackage.Items\"\x00\x62\x06proto3')



_VOIDNOPARAM = DESCRIPTOR.message_types_by_name['voidNoParam']
_ITEM = DESCRIPTOR.message_types_by_name['Item']
_ITEMS = DESCRIPTOR.message_types_by_name['Items']
voidNoParam = _reflection.GeneratedProtocolMessageType('voidNoParam', (_message.Message,), {
  'DESCRIPTOR' : _VOIDNOPARAM,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage.voidNoParam)
  })
_sym_db.RegisterMessage(voidNoParam)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage.Item)
  })
_sym_db.RegisterMessage(Item)

Items = _reflection.GeneratedProtocolMessageType('Items', (_message.Message,), {
  'DESCRIPTOR' : _ITEMS,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:grpcPackage.Items)
  })
_sym_db.RegisterMessage(Items)

_TODO = DESCRIPTOR.services_by_name['Todo']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOIDNOPARAM._serialized_start=27
  _VOIDNOPARAM._serialized_end=40
  _ITEM._serialized_start=42
  _ITEM._serialized_end=60
  _ITEMS._serialized_start=62
  _ITEMS._serialized_end=81
  _TODO._serialized_start=83
  _TODO._serialized_end=144
# @@protoc_insertion_point(module_scope)
